# Generated by Django 6.0.5 on 2026-09-01 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('category', models.CharField(default='Guides', max_length=60)),
                ('excerpt', models.TextField()),
                ('content', models.TextField(blank=True)),
                ('author', models.CharField(default='Encode Campus', max_length=80)),
                ('read_minutes', models.PositiveIntegerField(default=5)),
                ('published_date', models.DateField()),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('organisation', models.CharField(blank=True, max_length=160)),
                ('subject', models.CharField(blank=True, max_length=160)),
                ('message', models.TextField()),
                ('is_handled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('organisation', models.CharField(max_length=160)),
                ('designation', models.CharField(blank=True, max_length=120)),
                ('institution_type', models.CharField(choices=[('school', 'School'), ('college', 'College & University'), ('coaching', 'Coaching Centre'), ('group', 'Education Group / Multi-Campus')], default='school', max_length=20)),
                ('student_strength', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('city', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('current_system', models.CharField(blank=True, max_length=160)),
                ('primary_challenge', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('plan_interest', models.CharField(blank=True, max_length=40)),
                ('estimated_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('source', models.CharField(default='website', max_length=80)),
                ('segment', models.CharField(blank=True, choices=[('smb', 'SMB'), ('mid_market', 'Mid-market'), ('high_value', 'High value')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('demo_scheduled', 'Demo scheduled'), ('closed', 'Closed')], default='new', max_length=20)),
            ],
            options={
                'verbose_name': 'Demo request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=240)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('product', 'Product'), ('data', 'Data'), ('pricing', 'Pricing'), ('operations', 'Operations'), ('enterprise', 'Enterprise')], default='product', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('pillar', models.CharField(choices=[('people', 'People'), ('academics', 'Academics'), ('administration', 'Administration'), ('finance', 'Finance'), ('operations', 'Operations'), ('communication', 'Communication'), ('governance', 'Governance & Intelligence')], max_length=20)),
                ('icon', models.CharField(default='grid', help_text='Icon key used by the frontend', max_length=40)),
                ('tagline', models.CharField(max_length=200)),
                ('problem', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('capabilities', models.JSONField(default=list, help_text='List of capability strings')),
                ('benefits', models.JSONField(default=list, help_text='List of outcome strings')),
                ('seo_title', models.CharField(blank=True, max_length=160)),
                ('seo_description', models.CharField(blank=True, max_length=320)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_type', models.CharField(choices=[('school', 'School'), ('college', 'College & University'), ('coaching', 'Coaching Centre'), ('group', 'Education Group / Multi-Campus')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('headline', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('problems', models.JSONField(default=list)),
                ('highlights', models.JSONField(default=list)),
                ('modules', models.JSONField(default=list)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_type', models.CharField(choices=[('school', 'School'), ('college', 'College & University'), ('coaching', 'Coaching Centre'), ('group', 'Education Group / Multi-Campus')], max_length=20)),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField(max_length=60)),
                ('price_per_student', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price_caption', models.CharField(default='per active student / month', max_length=60)),
                ('positioning', models.CharField(blank=True, max_length=120)),
                ('is_popular', models.BooleanField(default=False)),
                ('cta_label', models.CharField(default='Book a Demo', max_length=40)),
                ('features', models.JSONField(default=list)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['institution_type', 'order'],
                'unique_together': {('institution_type', 'slug')},
            },
        ),
    ]
